### ISSUE TITLE
Using Jupytext to transform to / from ipynb

### ISSUE THREAD

**Issue by psychemedia** [notebook-sharing-space/nbss#14]
The `jupytext` package can round trip various rich code formats (md, MyST, Rmd, various py flavours etc) into ipynb (although cell outputs are not currently supported?).

Would it be appropriate to accept formats than can be mapped to ipynb?

Questions then arise as to whether`ipynb.pub` should:

- convert uploaded documents to ipynb and stores just that;
- retain the uploaded format as well as the converted-to ipynb format;

Are file downloads currently supported? (If so, should download of Jupytext convertable formats also be offered? This would add a document conversion as well as document sharing feature to `ipynb.pub` which might be better as a separate service?)

Also related: would an option to strip code outputs on uploaded ipynb docs be appropriate?

Also also related: Github has various tools for stripping secrets, including a new [convention based one](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/); should secret stripping (where possible) be applied to notebooks? Again, a question arises as to where rewriting uploaded files takes place.

**Comment by yuvipanda** [comment]
I am trying to make sure this can be run as cheaply as possible, and part of that involves reducing read-time transforms as much as possible. Write-time transforms are ok though! So the way to deal with this is to accept them for upload, convert them to a canonical format (ipynb), and just render from that.

Definitely should support whatever jupytext does!

**Comment by yuvipanda** [comment]
Actually looks pretty simple - see https://github.com/mwouts/jupytext/blob/4ae9263d3cb94fea9880a6b1676af81e91092399/jupytext/jupytext.py#L358

**Comment by yuvipanda** [comment]
ok, I've added support for `.md` and `.Rmd` as parsed by Jupytext. I want to only support 'notebook-like' formats. But I think now that includes .py and .jl files too, since some are percent encoded like that. Trying to figure out what the right thing here is.

**Comment by yuvipanda** [comment]
Based on https://github.com/mwouts/jupytext#which-text-format, i'll add .py and .jl support too

**Comment by yuvipanda** [comment]
Doing this conversion at write-time means any upgrades to the conversion process in jupytext won't be reflected here. Hmmmm.

**Comment by psychemedia** [comment]
One thing I have been wondering about lately relates to accessing OCRd PDFs from the Internet Archive. A lot of the extracted text seems like it was generated from OCR tools years ago - so the quality is not as good as it might be if OCR were run now.

Rerunning OCR on everything for every step change in OCR performance would be a waste of resource, but a lazy approach that reprocesses: a) frequently requested items, where b) the last text extraction date was more than a thresholded number of OCR versions ago would be more pragmatic. Users might also on-demand request an update, perhaps with no guarantee it would happen unless they made a micropayment.

Applying similar thinking to *ipynb.pub*, one solution might be to record a conversion date/Jupytext version and allow someone requesting the resource to request an updated conversion if they see that that Jupytext has been updated in the meantime (so also publish the currently version number of the currently Jupytext release for comparison).

Alternatively, you could on-demand update the conversion if someone requests a download of a particular format.

In each case, as metadata for the converted formats, it would be recording the conversion date and Jupytext version used for the conversion, perhaps even offering a history of versions?

**Comment by psychemedia** [comment]
@yuvipanda If you are using git to track uploaded documents, I seem to recall there has been quite a bit of discussion in the Jupytext issues about pre-commit based workflows using Jupytext as well as things like linters? Again, feature creep, but an upsell on *ipynb.pub* might be the option for a user to request various pre-commit operations being applied to an upload?

**Comment by yuvipanda** [comment]
With 107b084f3e81f6fe6c3b530a0916a07563319b59, I now:

1. Store the raw upload file, and don't convert on write. Bug fixes and updates in Jupytext parsing seem too good to let pass for perf gains here.
2. Store metadata - particularly, the uploaded file name. This lets us pass the extension to jupytext, making parsing easier. As a side effect, when you download the file, the original file name is retained.

Read-side caching is still important here to save cost, but I think this is a better decision for long term sustainability.

**Comment by yuvipanda** [comment]
I think this is done now!
