### ISSUE TITLE
robots.txt settings

### ISSUE THREAD

**Issue by psychemedia** [notebook-sharing-space/nbss#17]
Are search engine / bot crawler discovery limits requested in any way via `robots.txt`? Should they be? Is this a possible advanced / upsell feature (*"make my notebook discoverable: Y/N"* etc.)?

**Comment by yuvipanda** [comment]
Yeah, I think these should be private by default - noindex (https://developers.google.com/search/docs/advanced/crawling/block-indexing) is probably a better fit here, since we want to be able to control this on a per-notebook level.

**Comment by yuvipanda** [comment]
Uploads are now non-discoverable by default - you can check a box in the upload dialog to make it visible.
