### ISSUE TITLE
Internal server error if filename contains non-ascii characters

### ISSUE THREAD

**Issue by astrojuanlu** [notebook-sharing-space/nbss#35]
Thanks so much for nbss, it's so cool! 🚀 

I tried uploading a `Argüelles.ipynb` notebook and got a 5xx error. Renamed it to `Arguelles.ipynb`, [everything is working](https://notebooksharing.space/view/ca35f574b0e0a4832c7592ed20fcd941f4d442ec68a000bc23a662b58501555f)

**Comment by yuvipanda** [comment]
Thank you so much for reporting this, @astrojuanlu! Somehow I didn't see this on GitHub...

Looking at the logs, I see:

```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Non ascii characters found in S3 metadata for key "filename", value: "Argüelles.ipynb".  
S3 metadata can only contain ASCII characters.
```

**Comment by yuvipanda** [comment]
This works now! Check out https://notebooksharing.space/view/c62bf62cad5d9a8e1a2038e59a7c74c5097dd11dbc217c13ad3bae2b61362ede#displayOptions=. 

Thank you so much for reporting this, @astrojuanlu!
