### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by jimstigler** [notebook-sharing-space/nbss#70]
Every time I try to upload a notebook I get "Internal Server Error." Is it just me?

**Comment by yuvipanda** [comment]
ty for reporting it, @jimstigler! Not just you! Looking into it now

**Comment by yuvipanda** [comment]
@jimstigler fixed now! Thank you for reporting it :)

**Comment by jimstigler** [comment]
Thanks, Yuvi!Sent from my iPhoneOn Dec 2, 2024, at 12:03 PM, Yuvi Panda ***@***.***> wrote:﻿
@jimstigler fixed now! Thank you for reporting it :)
